import csv
import os

def escape_sql_string(value):
    if value is None or value == '':
        return 'NULL'
    # Escape single quotes
    return "'" + str(value).replace("'", "''") + "'"

def escape_sql_number(value):
    if value is None or value == '':
        return '0'
    return value

input_file = '/Users/zaki/Downloads/Oshop-main/users_v4_rows (2).csv'
output_file = '/Users/zaki/Downloads/Oshop-main/src/lib/import_users_v4.sql'

print(f"Reading {input_file}...")

with open(input_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    rows = list(reader)

print(f"Found {len(rows)} rows.")

sql_statements = []

sql_statements.append("-- =============================================")
sql_statements.append("-- Import Users from CSV (v4)")
sql_statements.append("-- Generated by Assistant")
sql_statements.append("-- =============================================")
sql_statements.append("")
sql_statements.append("BEGIN;")
sql_statements.append("")
sql_statements.append("-- 1. Ensure required columns exist")
sql_statements.append("DO $$")
sql_statements.append("BEGIN")
sql_statements.append("    -- Check/Add walletBalance")
sql_statements.append("    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'walletBalance') THEN")
sql_statements.append("        ALTER TABLE users ADD COLUMN \"walletBalance\" DECIMAL(10,2) DEFAULT 0.00;")
sql_statements.append("    END IF;")
sql_statements.append("")
sql_statements.append("    -- Check/Add created_at")
sql_statements.append("    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'created_at') THEN")
sql_statements.append("        ALTER TABLE users ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();")
sql_statements.append("    END IF;")
sql_statements.append("")
sql_statements.append("    -- Check/Add deleted_at")
sql_statements.append("    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'deleted_at') THEN")
sql_statements.append("        ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;")
sql_statements.append("    END IF;")
sql_statements.append("END $$;")
sql_statements.append("")

# Batch inserts for performance
batch_size = 100
for i in range(0, len(rows), batch_size):
    batch = rows[i:i+batch_size]
    
    sql_statements.append(f"-- Batch {i+1}-{i+len(batch)}")
    sql_statements.append("INSERT INTO users (id, name, username, password, phone, address, \"orderCount\", debt, \"orderCounter\", created_at, \"walletBalance\", deleted_at)")
    sql_statements.append("VALUES")
    
    values_list = []
    for row in batch:
        id_val = escape_sql_string(row['id'])
        name = escape_sql_string(row['name'])
        username = escape_sql_string(row['username'])
        password = escape_sql_string(row['password'])
        phone = escape_sql_string(row['phone'])
        address = escape_sql_string(row['address'])
        orderCount = escape_sql_number(row['orderCount'])
        debt = escape_sql_number(row['debt'])
        orderCounter = escape_sql_number(row['orderCounter'])
        created_at = escape_sql_string(row['created_at'])
        walletBalance = escape_sql_number(row['walletBalance'])
        deleted_at = escape_sql_string(row['deleted_at'])
        
        # Handle deleted_at being NULL string in CSV interpretation
        if row['deleted_at'] == '':
            deleted_at = 'NULL'

        line = f"({id_val}, {name}, {username}, {password}, {phone}, {address}, {orderCount}, {debt}, {orderCounter}, {created_at}, {walletBalance}, {deleted_at})"
        values_list.append(line)
    
    sql_statements.append(",\n".join(values_list))
    sql_statements.append("ON CONFLICT (id) DO UPDATE SET")
    sql_statements.append("    name = EXCLUDED.name,")
    sql_statements.append("    username = EXCLUDED.username,")
    sql_statements.append("    password = EXCLUDED.password,")
    sql_statements.append("    phone = EXCLUDED.phone,")
    sql_statements.append("    address = EXCLUDED.address,")
    sql_statements.append("    \"orderCount\" = EXCLUDED.\"orderCount\",")
    sql_statements.append("    debt = EXCLUDED.debt,")
    sql_statements.append("    \"orderCounter\" = EXCLUDED.\"orderCounter\",")
    sql_statements.append("    \"walletBalance\" = EXCLUDED.\"walletBalance\",")
    sql_statements.append("    updated_at = NOW();") 
    sql_statements.append("")

sql_statements.append("COMMIT;")
sql_statements.append("SELECT 'Successfully imported users.' as status;")

with open(output_file, 'w', encoding='utf-8') as f:
    f.write("\n".join(sql_statements))

print(f"Successfully generated {output_file}")
